server:
  address: 0.0.0.0
  port: 8080
  tomcat:
    threads:
      max: 200
      min-spare: 10
    max-connections: 8192
    accept-count: 100
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  rabbitmq:
#    host: linkus-rabbitmq
    host: localhost
    username: guest
    password: guest
    virtual-host: /

rabbitmq:
  queue:
    name: chat.queue
  exchange:
    name: chat.exchange
  routing:
    key: chatroom.*

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true