version: '3'
services:
  backend:
    env_file:
      - ../.env
    image: linkus:2
    container_name: linkus-2
    entrypoint:
      - "java"
      - "-Xlog:gc*"
      - "-jar"
      - "build/libs/backend-0.0.1-SNAPSHOT.jar"
    ports:
      - "8081:8080"
    networks:
      - monitoring
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "1"

  prometheus:
    image: prom/prometheus
    container_name: linkus-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
    depends_on:
      - backend
    restart: always

  rabbitmq:
    image: rabbitmq:management
    container_name: linkus-rabbitmq
    hostname: linkus-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitmqCookie
    networks:
      - monitoring

  rabbitmq2:
    image: rabbitmq:management
    container_name: linkus-rabbitmq2
    hostname: linkus-rabbitmq2
    ports:
      - "5673:5672"
      - "15673:15672"
      - "61614:61613"
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitmqCookie
    networks:
      - monitoring

  rabbitmq3:
    image: rabbitmq:management
    container_name: linkus-rabbitmq3
    hostname: linkus-rabbitmq3
    ports:
      - "5674:5672"
      - "15674:15672"
      - "61615:61613"
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitmqCookie
    networks:
      - monitoring

networks:
  monitoring:
    external: true