global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'  # Spring Boot의 Prometheus 엔드포인트
    static_configs:
      - targets: [ 'backend:8080' ]  # Spring Boot 애플리케이션의 주소
#      - targets: [ 'host.docker.internal:8080' ]  # Spring Boot 애플리케이션의 주소